// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttqymkogjfqvddwtophq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cXlta29namZxdmRkd3RvcGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODY4ODcsImV4cCI6MjA2ODM2Mjg4N30.8tYIDor59VIUsQ3p0EXsSiQ4p1MCkOthsfjivbkB30g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});